# https://docs.gradle.org/8.11/userguide/version_catalogs.html

[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }

[versions]
jtreesitter = "0.25.6"
junit = "6.0.1"

[libraries]
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version = "3.0.3" }
# Don't use official JavaPoet because it is not actively maintained anymore, see https://github.com/square/javapoet/discussions/866
# Instead uses https://github.com/palantir/javapoet
javapoet = { module = "com.palantir.javapoet:javapoet", version = "0.10.0" }
jtreesitter = { module = "io.github.tree-sitter:jtreesitter", version.ref = "jtreesitter" }

compilerTesting = { module = "io.github.ascopes.jct:java-compiler-testing", version = "6.0.0" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.17" }
assertj = { module = "org.assertj:assertj-core", version = "3.27.7" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
# No version; specified by BOM above
junit = { module = "org.junit.jupiter:junit-jupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher" }

picocli = { module = "info.picocli:picocli", version = "4.7.7" }
